name: ATMA IP
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56087
title: ATMA Intellectual Property
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#66004c'
    - '#e5c2df'
    - '#666666'
    - '#a0a0a0'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
