name: ATMA IP
favicon: null
layout_spectrum: 0.35953
typography_spectrum: 0.56087
title: ATMA Intellectual Property
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#66004c'
    - '#b3b3b3'
    - '#ffffff'
    - '#785a73'
    - '#7d2767'
  brandStrength: 0.8125
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
